export const labCopy = {
  preview: 'Repair Map', homeTitle: 'Your next walk starts here.',
  homeIntro: 'Repairs, rollouts, and placement checks. Every photo in its place.',
  local: 'Saved on this device', homeSearch: 'Find a site or walk',
  sample: 'Explore a sample walk', loading: 'Preparing sample…',
  sampleNote: 'Fictional site and illustrated photos. Safe to experiment.',
  sites: 'Your walks', noMatches: 'No walks match your search.',
  map: 'Back to map', details: 'Show details', collapse: 'Collapse details',
  search: 'Find an area, item, or note', noSpots: 'No spots match. Try another search or status.',
  backup: 'Save a backup', report: 'Generate report', checklist: 'Checklist',
  previous: 'Previous spot', next: 'Next spot', photoGap: 'Show spots without photos',
  photosReady: 'Every spot has a photo', addFirst: 'Drop your first pin to start the walk.',
  remaining: 'Next unchecked spot', allChecked: 'Every spot has been checked',
  overview: 'Walk overview', cancel: 'Cancel', mapPreview: 'Floor plan preview',
  covered: (n: number, total: number) => `${n} of ${total} spots have photos`,
  checked: (n: number, total: number) => `${n} of ${total} spots checked`,
  missingPhotos: (n: number) => `${n} ${n === 1 ? 'spot needs' : 'spots need'} photos`,
  counts: (spots: number, photos: number) => `${spots} spots · ${photos} photos`,
  siteCount: (n: number) => `${n} ${n === 1 ? 'walk' : 'walks'} on this device`,
}
